config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :rewards
  resources :dailies
  resources :notes
  resources :todos
  resources :habits
  resources :tags
  resources :tags
  resources :trials
  get "records", :to => 'records#index'
  put "records", :to => 'records#update'
  patch "records", :to => 'records#update'
  devise_for :users

  namespace :auth do # API Login
    devise_scope :user do
      post "/sign_in", :to => 'sessions#create'
      post "/sign_up", :to => 'registrations#create'
      delete "/sign_out", :to => 'sessions#destroy'
    end
  end
  # root path
  root 'static_pages#home'
end

app/models/daily.rb
class Daily < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init
	
    def init
 		self.streak 	||= 0
 		self.difficulty ||= 0
 		self.priority 	||= 0
 		self.monday		||= false
 		self.tuesday 	||= false
 		self.wednesday  ||= false
 		self.thursday   ||= false
 		self.friday 	||= false
 		self.saturday 	||= false
 		self.sunday 	||= false
 		self.done 	 	||= 0
    end
    validates :title, presence: true
	validates :difficulty, numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/habit.rb
class Habit < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init

    def init
 		self.streak ||= 0
 		self.difficulty ||= 0
 		self.priority ||=0
    end
    validates :title, presence: true
	validates :difficulty, numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	validates :title, presence: true
	after_initialize :init
	def init
		self.important ||= false
	end
end

app/models/record.rb
class Record < ActiveRecord::Base
	belongs_to :user
end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :user
	after_initialize :init

    def init
 		self.price ||= 10
    end
    validates :title, presence: true
    validates :price, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :trials
	has_and_belongs_to_many :habits
	has_and_belongs_to_many :todos
	has_and_belongs_to_many :dailies 
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init

    def init
 		self.difficulty  ||= 0
 		self.priority    ||= 0
 		self.done	   	 ||= 0
    end
    validates :title, presence: true
	validates :difficulty, numericality: {greater_than_equal_to: 0,less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/trial.rb
class Trial < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init

    def init
 		self.streak ||= 0
    end
	validates :diff, numericality: { less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :trials
  has_many :habits
  has_many :todos
  has_many :tags
  has_many :notes
  has_many :rewards
  has_many :dailies
  has_one :record
  after_create :init
  before_destroy :removeRecord

  def init
    Record.create(:health => 100, :experience => 0, :level => 0, :gold => 0, :silver => 0, :diamonds => 0, :user_id => self.id, )
  end

  def removeRecord
    Record.find(User.find(self.id).record.id).delete
  end
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_user_from_token!

  # GET /notes
  # GET /notes.json
  def index
    @notes = current_user.notes
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def correct_user
      @note = current_user.notes.find_by(id: params[:id])
      redirect_to notes_path if @note.nil?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :data, :important, { :tag_ids => []})
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_user_from_token!

  # GET /tags
  # GET /tags.json
  def index
    @tags = current_user.tags
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = current_user.tags.build
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = current_user.tags.build(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def correct_user
      @tag = current_user.tags.find_by(id: params[:id])
      redirect_to tags_path if @tag.nil?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_area :data %>
  </div>
  <div class="field">
    <div class="field_head">Tags</div>
      <%= hidden_field_tag("note[tag_ids][]", nil) %>
      <% current_user.tags.order(:name).each do |tag| %>
          <label><%= check_box_tag("note[tag_ids][]", tag.id, @note.tag_ids.include?(tag.id))  %> 
          <%= tag.name %></label>
      <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.data %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Data:</strong>
  <%= @note.data %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>