config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :rewards
  resources :dailies
  resources :notes
  resources :todos
  resources :habits
  resources :tags
  resources :tags
  resources :trials
  get "records", :to => 'records#index'
  put "records", :to => 'records#update'
  patch "records", :to => 'records#update'
  devise_for :users

  namespace :auth do # API Login
    devise_scope :user do
      post "/sign_in", :to => 'sessions#create'
      post "/sign_up", :to => 'registrations#create'
      delete "/sign_out", :to => 'sessions#destroy'
    end
  end
  # root path
  root 'static_pages#home'
end

app/models/daily.rb
class Daily < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init
	
    def init
 		self.streak 	||= 0
 		self.difficulty ||= 0
 		self.priority 	||= 0
 		self.monday		||= false
 		self.tuesday 	||= false
 		self.wednesday  ||= false
 		self.thursday   ||= false
 		self.friday 	||= false
 		self.saturday 	||= false
 		self.sunday 	||= false
 		self.done 	 	||= 0
    end
    validates :title, presence: true
	validates :difficulty, numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/habit.rb
class Habit < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init

    def init
 		self.streak ||= 0
 		self.difficulty ||= 0
 		self.priority ||=0
    end
    validates :title, presence: true
	validates :difficulty, numericality: {greater_than_or_equal_to: 0,less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	validates :title, presence: true
	after_initialize :init
	def init
		self.important ||= false
	end
end

app/models/record.rb
class Record < ActiveRecord::Base
	belongs_to :user
end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :user
	after_initialize :init

    def init
 		self.price ||= 10
    end
    validates :title, presence: true
    validates :price, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :trials
	has_and_belongs_to_many :habits
	has_and_belongs_to_many :todos
	has_and_belongs_to_many :dailies 
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init

    def init
 		self.difficulty  ||= 0
 		self.priority    ||= 0
 		self.done	   	 ||= 0
    end
    validates :title, presence: true
	validates :difficulty, numericality: {greater_than_equal_to: 0,less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/trial.rb
class Trial < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :tags
	after_initialize :init

    def init
 		self.streak ||= 0
    end
	validates :diff, numericality: { less_than_or_equal_to: 4,:allow_blank => true}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :trials
  has_many :habits
  has_many :todos
  has_many :tags
  has_many :notes
  has_many :rewards
  has_many :dailies
  has_one :record
  after_create :init
  before_destroy :removeRecord

  def init
    Record.create(:health => 100, :experience => 0, :level => 0, :gold => 0, :silver => 0, :diamonds => 0, :user_id => self.id, )
  end

  def removeRecord
    Record.find(User.find(self.id).record.id).delete
  end
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoNow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if !user_signed_in? %>
<%= link_to("Sign In", new_user_session_path) %>
<%= link_to("Sign Up", new_user_registration_path) %>
<% else %>
<%= link_to("Logout", destroy_user_session_path , method: :delete) %>
<%= link_to("Edit Account", edit_user_registration_path) %>
<%= link_to("Home", root_path) %>
<%= link_to("Rewards", rewards_path) %>
<%= link_to("Dailies", dailies_path) %>
<%= link_to("Habits", habits_path) %>
<%= link_to("Notes", notes_path) %>
<%= link_to("To-do", todos_path) %>
<%= link_to("Trials", trials_path) %>
<%= link_to("Tags", tags_path) %>
Health : <%= current_user.record.health %>
Experience : <%= current_user.record.experience %>
Level : <%= current_user.record.level %>
<% end %>
<hr>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>